[target.aarch64-linux-android]
ar = "C:\\Users\\Ares\\AppData\\Local\\Android\\Sdk\\ndk\\22.1.7171670\\toolchains\\llvm\\prebuilt\\windows-x86_64\\aarch64-linux-android\\bin\\ar.exe"
linker = "C:\\Users\\Ares\\AppData\\Local\\Android\\Sdk\\ndk\\22.1.7171670\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\aarch64-linux-android29-clang.cmd"

[target.armv7-linux-androideabi]
ar = "C:\\Users\\Ares\\AppData\\Local\\Android\\Sdk\\ndk\\22.1.7171670\\toolchains\\llvm\\prebuilt\\windows-x86_64\\armv7-linux-androideabi\\bin\\ar.exe"
linker = "C:\\Users\\Ares\\AppData\\Local\\Android\\Sdk\\ndk\\22.1.7171670\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\armv7a-linux-androideabi29-clang.cmd"

[target.i686-linux-android]
ar = "C:\\Users\\Ares\\AppData\\Local\\Android\\Sdk\\ndk\\22.1.7171670\\toolchains\\llvm\\prebuilt\\windows-x86_64\\i686-linux-android\\bin\\ar.exe"
linker = "C:\\Users\\Ares\\AppData\\Local\\Android\\Sdk\\ndk\\22.1.7171670\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\i686-linux-android29-clang.cmd"

[target.x86_64-linux-android]
ar = "C:\\Users\\Ares\\AppData\\Local\\Android\\Sdk\\ndk\\22.1.7171670\\toolchains\\llvm\\prebuilt\\windows-x86_64\\x86_64-linux-android\\bin\\ar.exe"
linker = "C:\\Users\\Ares\\AppData\\Local\\Android\\Sdk\\ndk\\22.1.7171670\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\x86_64-linux-android29-clang.cmd"
